/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  chains: [
    {
      type: "link",
      label: "Overview",
      href: "/chains",
    },
    {
      type: "category",
      label: "Chain Guides",
      collapsed: true,
      collapsible: true,
      items: [
        {
          type: "autogenerated",
          dirName: "chains",
        },
      ],
    },
  ],
};

module.exports = sidebars;
