/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually

  go: [
    {
      type: "doc",
      label: "Getting Started",
      id: "index",
    },
    {
      type: "doc",
      label: "ThirdwebSDK",
      id: "sdk",
    },
    {
      type: "doc",
      label: "IPFS Storage",
      id: "storage",
    },
    {
      type: "category",
      label: "Contracts",
      collapsed: false,
      link: {
        type: "generated-index",
        title: "Contracts",
        description: "Interfaces for on-chain contracts.",
        keywords: ["contracts"],
      },
      items: [
        {
          type: "doc",
          label: "NFT Collection",
          id: "nft_collection",
        },
        {
          type: "doc",
          label: "Edition",
          id: "edition",
        },
        {
          type: "doc",
          label: "Token",
          id: "token",
        },
        {
          type: "doc",
          label: "NFT Drop",
          id: "nft_drop",
        },
        {
          type: "doc",
          label: "Edition Drop",
          id: "edition_drop",
        },
      ],
    },
    {
      type: "category",
      label: "Contract Interfaces",
      collapsed: true,
      link: {
        type: "generated-index",
        title: "Contract Interfaces",
        description:
          "Contract interfaces that extend the functionality of contracts.",
        keywords: ["contracts", "shared-interfaces"],
      },
      items: [
        {
          type: "doc",
          label: "ERC 20",
          id: "erc20",
        },
        {
          type: "doc",
          label: "ERC 721",
          id: "erc721",
        },
        {
          type: "doc",
          label: "ERC 1155",
          id: "erc1155",
        },
      ],
    },
    {
      type: "category",
      label: "Signature Minting",
      collapsed: true,
      link: {
        type: "generated-index",
        title: "Signature Minting",
        description: "Signature based minting for contracts.",
        keywords: ["contracts", "signature-minting"],
      },
      items: [
        {
          type: "doc",
          label: "ERC 721 Signature Minting",
          id: "erc721_signature_minting",
        },
        {
          type: "doc",
          label: "ERC 1155 Signature Minting",
          id: "erc1155_signature_minting",
        },
      ],
    },
  ],
};

module.exports = sidebars;
