/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually

  onboarding: [
    {
      type: "doc",
      label: "Home",
      id: "0 0 Home",
    },
    {
      type: "doc",
      label: "Overview ",
      id: "0 1 Platform Overview",
    },
    {
      type: "link",
      label: "Getting Started",
      href: "/getting-started",
    },
    {
      type: "link",
      label: "Solidity SDK",
      href: "/solidity",
    },
    {
      type: "link",
      label: "Publish",
      href: "/publish",
    },
    {
      type: "doc",
      label: "Deploy",
      id: "6 Deploy",
    },
    {
      type: "link",
      label: "Explore",
      href: "/pre-built-contracts",
    },
    {
      type: "link",
      label: "EVM SDK",
      href: "/sdk",
    },
    {
      type: "link",
      label: "UI Components",
      href: "/react/react.connectwallet",
    },
    {
      type: "link",
      label: "Solana SDK",
      href: "/solana",
    },
    {
      type: "link",
      label: "GamingKit",
      href: "/gamingkit",
    },
    {
      type: "link",
      label: "CommerceKit",
      href: "/commercekit",
    },
    {
      type: "link",
      label: "Auth",
      href: "/auth",
    },
    {
      type: "link",
      label: "Storage",
      href: "/storage",
    },
    {
      type: "link",
      label: "Dashboard",
      href: "/dashboard",
    },
    {
      type: "link",
      label: "CLI",
      href: "/cli",
    },
    {
      type: "link",
      label: "Glossary",
      href: "/glossary",
    },
    {
      type: "doc",
      label: "Templates",
      id: "14 Templates",
    },
    {
      type: "link",
      label: "Guides",
      href: "https://blog.thirdweb.com/guides/",
    },
    {
      type: "link",
      label: "React",
      href: "/react",
    },
    {
      type: "link",
      label: "TypeScript",
      href: "/typescript",
    },
    {
      type: "link",
      label: "React Native",
      href: "/react-native",
    },
    {
      type: "link",
      label: "Python",
      href: "/python",
    },
    {
      type: "link",
      label: "Go",
      href: "/go",
    },
    {
      type: "link",
      label: "Unity",
      href: "/unity",
    },
    {
      type: "link",
      label: "Solidity",
      href: "/solidity",
    },
  ],

  gettingStarted: [
    {
      type: "autogenerated",
      dirName: "0 Getting Started",
    },
  ],

  buildContracts: [
    {
      type: "autogenerated",
      dirName: "1 Solidity SDK",
    },
  ],

  prebuiltContracts: [
    {
      type: "autogenerated",
      dirName: "2 Explore",
    },
  ],

  sdk: [
    {
      type: "doc",
      label: "Overview",
      id: "3 EVM SDK/0 Overview",
    },
    {
      type: "doc",
      label: "Architecture",
      id: "3 EVM SDK/1 How it works",
    },
    {
      type: "category",
      label: "SDK References",
      items: [
        {
          type: "link",
          href: "/react",
          label: "React",
        },
        {
          type: "link",
          href: "/react-native",
          label: "React Native",
        },
        {
          type: "link",
          href: "/typescript",
          label: "TypeScript",
        },
        {
          type: "link",
          href: "/python",
          label: "Python",
        },
        {
          type: "link",
          href: "/go",
          label: "Go",
        },
        {
          type: "link",
          href: "/unity",
          label: "Unity",
        },
      ],
    },
  ],

  publish: [
    {
      type: "autogenerated",
      dirName: "7 Publish",
    },
  ],

  dashboard: [
    {
      type: "autogenerated",
      dirName: "8 Dashboard",
    },
  ],

  cli: [
    {
      type: "autogenerated",
      dirName: "9 CLI",
    },
  ],

  auth: [
    {
      type: "autogenerated",
      dirName: "10 Auth",
    },
  ],

  storage: [
    {
      type: "autogenerated",
      dirName: "11 Storage",
    },
  ],

  solana: [
    {
      type: "autogenerated",
      dirName: "4 Solana SDK",
    },
  ],

  commerce: [
    {
      type: "autogenerated",
      dirName: "12 Commerce",
    },
  ],

  gaming: [
    {
      type: "autogenerated",
      dirName: "13 Gaming",
    },
  ],

  glossary: [
    {
      type: "autogenerated",
      dirName: "15 Glossary",
    },
  ],
};

module.exports = sidebars;
