/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually

  python: [
    {
      type: "doc",
      label: "Overview",
      id: "index",
    },
    {
      type: "doc",
      label: "Getting Started",
      id: "getting-started",
    },
    // ThirdwebSDK
    {
      type: "category",
      label: "ThirdwebSDK",
      collapsed: false,
      items: [
        {
          type: "doc",
          label: "Overview",
          id: "thirdwebsdk",
        },
        {
          type: "doc",
          label: "fromPrivateKey",
          id: "thirdwebsdk.fromprivatekey",
        },
      ],
    },
    // Deploying Contracts
    {
      type: "doc",
      label: "Contract Deployer",
      id: "contract-deployer",
    },
    // Interacting with contracts
    {
      type: "category",
      label: "Interacting with Contracts",
      collapsed: false,
      items: [
        {
          type: "doc",
          label: "Overview",
          id: "interacting-with-contracts/0 Overview",
        },
        {
          type: "doc",
          label: "Using Custom Contracts",
          id: "interacting-with-contracts/call",
        },
        {
          type: "doc",
          label: "Using Custom Contracts",
          id: "interacting-with-contracts/get",
        },
        {
          type: "category",
          label: "Using Extensions",
          items: [
            {
              type: "category",
              label: "ERC721",
              items: [
                {
                  type: "autogenerated",
                  dirName: "interacting-with-contracts/extensions/erc721",
                },
              ],
            },
            {
              type: "category",
              label: "ERC1155",
              items: [
                {
                  type: "autogenerated",
                  dirName: "interacting-with-contracts/extensions/erc1155",
                },
              ],
            },
            {
              type: "category",
              label: "ERC20",
              items: [
                {
                  type: "autogenerated",
                  dirName: "interacting-with-contracts/extensions/erc20",
                },
              ],
            },
            {
              type: "autogenerated",
              dirName: "interacting-with-contracts/extensions/general",
            },
          ],
        },
        {
          type: "category",
          label: "Using Prebuilt Contracts",
          items: [
            {
              type: "autogenerated",
              dirName: "interacting-with-contracts/prebuilt-contracts",
            },
          ],
        },
      ],
    },
    // Contract Events
    {
      type: "doc",
      label: "Contract Events",
      id: "contract-events",
    },
    // User Wallet
    {
      type: "doc",
      label: "Wallet Authenticator",
      id: "wallet-authenticator",
    },
    // Storage
    {
      type: "doc",
      label: "Storage",
      id: "storage",
    },
  ]
};

module.exports = sidebars;
