/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually

  typescript: [
    {
      type: "doc",
      label: "Getting Started",
      id: "index",
    },
    {
      type: "category",
      label: "Wallet Connection",
      link: {
        type: "generated-index",
        title: "Wallet Connection",
        description:
          "Hooks to let users connect and disconnect their wallets.",
        keywords: ["wallet", "connection"],
      },
      collapsed: true,
      items: [
        {
          type: "doc",
          label: "useMetamask",
          id: "react.usemetamask",
        },
        {
          type: "doc",
          label: "useWalletConnect",
          id: "react.usewalletconnect",
        },
        {
          type: "doc",
          label: "useCoinbaseWallet",
          id: "react.usecoinbasewallet",
        },
        {
          type: "doc",
          label: "useMagic",
          id: "react.usemagic",
        },
        {
          type: "doc",
          label: "useDisconnect",
          id: "react.usedisconnect",
        },
      ],
    },
    {
      type: "category",
      label: "Wallet Info",
      link: {
        type: "generated-index",
        title: "Wallet Info",
        description:
          "Hooks to get information about the connected wallet.",
        keywords: ["wallet", "info"],
      },
      items: [
        {
          type: "doc",
          label: "useAddress",
          id: "react.useaddress",
        },
        {
          type: "doc",
          label: "useChainId",
          id: "react.usechainid",
        },
        {
          type: "doc",
          label: "useNetworkMismatch",
          id: "react.usenetworkmismatch",
        },
      ]
    },
    {
      type: "category",
      label: "Contracts",
      collapsed: true,
      link: {
        type: "generated-index",
        title: "Contracts Hooks",
        description: "Hooks to interact with thirdweb contracts and sdk",
        keywords: ["general", "hooks"],
      },
      items: [
        {
          type: "doc",
          label: "useEdition",
          id: "react.useedition",
        },
        {
          type: "doc",
          label: "useEditionDrop",
          id: "react.useeditiondrop",
        },
        {
          type: "doc",
          label: "useMarketplace",
          id: "react.usemarketplace",
        },
        {
          type: "doc",
          label: "useNFTCollection",
          id: "react.usenftcollection",
        },
        {
          type: "doc",
          label: "useNFTDrop",
          id: "react.usenftdrop",
        },
        {
          type: "doc",
          label: "usePack",
          id: "react.usepack",
        },
        {
          type: "doc",
          label: "useSplit",
          id: "react.usesplit",
        },
        {
          type: "doc",
          label: "useToken",
          id: "react.usetoken",
        },
        {
          type: "doc",
          label: "useVote",
          id: "react.usevote",
        },
      ],
    },
    {
      type: "category",
      label: "Components",
      collapsed: true,
      link: {
        type: "generated-index",
        title: "Components",
        description: "Convenient react components that give you out-of-the-box functionality",
        keywords: ["general", "hooks"],
      },
      items: [
        {
          type: "doc",
          label: "Media Renderer",
          id: "react.mediarenderer",
        },
      ],
    },
  ],
};

module.exports = sidebars;
