/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually

  "react-native": [
    {
      type: "doc",
      label: "Installation",
      id: "index",
    },
    {
      type: "doc",
      label: "Getting Started",
      id: "getting-started",
    },
    {
      type: "category",
      label: "UI Components",
      collapsed: false,
      items: [
        {
          type: "doc",
          label: "Connect Wallet Button",
          id: "ui-components/ConnectWallet",
        },
        {
          type: "doc",
          label: "Web3 Button",
          id: "ui-components/Web3Button",
        },
      ],
    },
    {
      type: "doc",
      label: "Available Hooks",
      id: "available-hooks",
    },
  ],
};

module.exports = sidebars;
