/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually

  "react-native": [
    {
      type: "doc",
      label: "Installation",
      id: "index",
    },
    {
      type: "doc",
      label: "Getting Started",
      id: "getting-started",
    },
    {
      type: "category",
      label: "Wallets",
      collapsed: false,
      items: [
        {
          type: "doc",
          label: "Embedded Wallet",
          id: "wallets/EmbeddedWallet",
        },
        {
          type: "doc",
          label: "Smart Wallet",
          id: "wallets/SmartWallet",
        },
        {
          type: "doc",
          label: "Wallet Connect",
          id: "wallets/WalletConnect",
        },
        {
          type: "doc",
          label: "MetaMask",
          id: "wallets/MetaMask",
        },
        {
          type: "doc",
          label: "Magic",
          id: "wallets/Magic",
        },
        {
          type: "doc",
          label: "Rainbow",
          id: "wallets/Rainbow",
        },
        {
          type: "doc",
          label: "Trust",
          id: "wallets/Trust",
        },
        {
          type: "doc",
          label: "Coinbase",
          id: "wallets/Coinbase",
        },
        {
          type: "doc",
          label: "Local Wallet",
          id: "wallets/LocalWallet",
        },
      ],
    },
    {
      type: "category",
      label: "UI Components",
      collapsed: false,
      items: [
        {
          type: "doc",
          label: "Connect Wallet Button",
          id: "ui-components/ConnectWallet",
        },
        {
          type: "doc",
          label: "Web3 Button",
          id: "ui-components/Web3Button",
        },
      ],
    },
    {
      type: "doc",
      label: "Available Hooks",
      id: "available-hooks",
    },
    // === Auth === \\
    {
      type: "category",
      label: "Auth",
      collapsed: false,
      items: [
        {
          type: "doc",
          label: "useLogin",
          id: "auth/uselogin",
        },
        {
          type: "doc",
          label: "useLogout",
          id: "auth/uselogout",
        },
        {
          type: "doc",
          label: "useUser",
          id: "auth/useuser",
        },
      ],
    },
    {
      type: "doc",
      label: "Storage",
      id: "storage",
    },
    {
      type: "category",
      label: "FAQ",
      collapsed: false,
      items: [
        {
          type: "doc",
          label: "How to enable Deep Links?",
          id: "faq/deeplinks",
        },
      ],
    },
    // Full Reference
    {
      type: "html",
      value:
        '<a style="text-decorations:none; color:inherit;" href="/reference/react-native/index.html" target="_blank">Full Reference</a>',
      defaultStyle: true,
    },
  ],
};

module.exports = sidebars;
