/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually

  solana: [
    {
      type: "doc",
      label: "Getting Started",
      id: "index",
    },
    {
      type: "doc",
      label: "ThirdwebSDK",
      id: "solana.thirdwebsdk",
    },
    {
      type: "doc",
      label: "Wallet Actions",
      id: "solana.userwallet",
    },
    {
      type: "doc",
      label: "Deploying Programs",
      id: "solana.deployer",
    },
    {
      type: "doc",
      label: "Custom Programs",
      id: "solana.program",
    },
    {
      type: "category",
      label: "Prebuilt Programs",
      collapsed: false,
      link: {
        type: "generated-index",
        title: "Prebuilt Programs",
        description: "Interfaces for on-chain contracts.",
        keywords: ["contracts"],
      },
      items: [
        {
          type: "doc",
          label: "NFT Collection",
          id: "solana.nftcollection",
        },
        {
          type: "doc",
          label: "NFT Drop",
          id: "solana.nftdrop",
        },
        {
          type: "doc",
          label: "Token",
          id: "solana.token",
        },
      ],
    },
  ],
};

module.exports = sidebars;
