/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually

  storage: [
    {
      type: "doc",
      label: "Getting Started",
      id: "index",
    },
    {
      type: "doc",
      label: "Thirdweb Storage",
      id: "storage.thirdwebstorage",
    },
    {
      type: "category",
      label: "Uploaders",
      collapsed: false,
      link: {
        type: "generated-index",
        title: "Uploaders",
        description:
          "Handle uploading data to different decentralized storage systems",
        keywords: ["storage", "uploaders"],
      },
      items: [
        {
          type: "doc",
          label: "IPFS Uploader",
          id: "storage.ipfsuploader",
        },
      ],
    },
    {
      type: "category",
      label: "Downloaders",
      collapsed: false,
      link: {
        type: "generated-index",
        title: "Downloaders",
        description:
          "Handle downloading data from decentralized storage systems",
        keywords: ["storage", "downloaders"],
      },
      items: [
        {
          type: "doc",
          label: "Storage Downloader",
          id: "storage.storagedownloader",
        },
      ],
    },
  ],
};

module.exports = sidebars;
