/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually

  typescript: [
    {
      type: "doc",
      label: "Getting Started",
      id: "index",
    },
    {
      type: "doc",
      label: "Migration Guide",
      id: "migration-guide",
    },

    // ThirdwebSDK
    {
      type: "category",
      label: "Initializing the SDK",
      items: [
        {
          type: "doc",
          label: "From Private Key (Backend)",
          id: "sdk.thirdwebsdk.fromprivatekey",
        },
        {
          type: "doc",
          label: "From Signer",
          id: "sdk.thirdwebsdk.fromsigner",
        },
        {
          type: "doc",
          label: "All SDK Options",
          id: "sdk.sdkoptions",
        },
      ],
    },

    // Interacting with contracts
    {
      type: "category",
      label: "Interacting with Contracts",
      collapsed: false,
      items: [
        {
          type: "doc",
          label: "Overview",
          id: "interacting-with-contracts/0 Overview",
        },
        {
          type: "doc",
          label: "Get A Contract",
          id: "interacting-with-contracts/thirdwebsdk.smartcontract",
        },
        {
          type: "doc",
          label: "Call Contract Functions",
          id: "interacting-with-contracts/thirdwebsdk.smartcontract.call",
        },
        {
          type: "doc",
          label: "Transaction Builder",
          id: "interacting-with-contracts/thirdwebsdk.smartcontract.prepare", // ???
        },
        {
          type: "doc",
          label: "Detecting Contract Extensions",
          id: "interacting-with-contracts/thirdwebsdk.smartcontract.detectfeatures", // ???
        },
        {
          type: "category",
          label: "Using Extensions",
          items: [
            {
              type: "category",
              label: "ERC721",
              items: [
                {
                  type: "autogenerated",
                  dirName: "interacting-with-contracts/extensions/erc721",
                },
              ],
            },
            {
              type: "category",
              label: "ERC1155",
              items: [
                {
                  type: "autogenerated",
                  dirName: "interacting-with-contracts/extensions/erc1155",
                },
              ],
            },
            {
              type: "category",
              label: "ERC20",
              items: [
                {
                  type: "autogenerated",
                  dirName: "interacting-with-contracts/extensions/erc20",
                },
              ],
            },
            {
              type: "autogenerated",
              dirName: "interacting-with-contracts/extensions/general",
            },
          ],
        },
        {
          type: "category",
          label: "Using Prebuilt Contracts",
          items: [
            {
              type: "autogenerated",
              dirName: "interacting-with-contracts/prebuilt-contracts",
            },
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
