/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually

  typescript: [
    {
      type: "doc",
      label: "Getting Started",
      id: "index",
    },

    // === Initializing the SDK ===
    {
      type: "category",
      label: "Initializing the SDK",
      items: [
        {
          type: "doc",
          label: "From Private Key (Backend)",
          id: "sdk.thirdwebsdk.fromprivatekey",
        },
        {
          type: "doc",
          label: "From Signer",
          id: "sdk.thirdwebsdk.fromsigner",
        },
        {
          type: "doc",
          label: "All SDK Options",
          id: "sdk.sdkoptions",
        },
      ],
    },
    // === Deploying A Contract ===
    {
      type: "category",
      label: "Deploying Contracts",
      items: [
        {
          type: "doc",
          label: "Contract Deployer",
          id: "sdk.contractdeployer",
        },
        {
          type: "doc",
          label: "Deploy A Released Contract",
          id: "sdk.contractdeployer.deployreleasedcontract",
        },
        {
          type: "doc",
          label: "Deploy Via Factory (Proxy)",
          id: "sdk.contractdeployer.deployviafactory",
        },
        {
          type: "category",
          label: "Prebuilt Contracts",
          items: [
            {
              type: "doc",
              label: "Edition",
              id: "sdk.contractdeployer.deployedition",
            },
            {
              type: "doc",
              label: "Edition Drop",
              id: "sdk.contractdeployer.deployeditiondrop",
            },
            {
              type: "doc",
              label: "Marketplace",
              id: "sdk.contractdeployer.deploymarketplace",
            },
            {
              type: "doc",
              label: "Multiwrap",
              id: "sdk.contractdeployer.deploymultiwrap",
            },
            {
              type: "doc",
              label: "NFT Collection",
              id: "sdk.contractdeployer.deploynftcollection",
            },
            {
              type: "doc",
              label: "NFT Drop",
              id: "sdk.contractdeployer.deploynftdrop",
            },
            {
              type: "doc",
              label: "Pack",
              id: "sdk.contractdeployer.deploypack",
            },
            {
              type: "doc",
              label: "Signature Drop",
              id: "sdk.contractdeployer.deploysignaturedrop",
            },
            {
              type: "doc",
              label: "Split",
              id: "sdk.contractdeployer.deploysplit",
            },
            {
              type: "doc",
              label: "Token",
              id: "sdk.contractdeployer.deploytoken",
            },
            {
              type: "doc",
              label: "Token Drop",
              id: "sdk.contractdeployer.deploytokendrop",
            },
            {
              type: "doc",
              label: "Vote",
              id: "sdk.contractdeployer.deployvote",
            },
          ],
        },
      ],
    },
    // === Getting A Contract ===
    {
      type: "category",
      label: "Getting a Contract",
      items: [
        {
          type: "doc",
          label: "Get A Contract",
          id: "sdk.thirdwebsdk.getcontract",
        },
        {
          type: "doc",
          label: "Get Contract From ABI",
          id: "sdk.thirdwebsdk.getcontractfromabi",
        },
        {
          type: "doc",
          label: "Get All Deployed Contracts",
          id: "sdk.thirdwebsdk.getcontractlist",
        },
        {
          type: "category",
          label: "Prebuilt Contracts",
          items: [
            {
              type: "doc",
              label: "Edition",
              id: "sdk.thirdwebsdk.getedition",
            },
            {
              type: "doc",
              label: "Edition Drop",
              id: "sdk.thirdwebsdk.geteditiondrop",
            },
            {
              type: "doc",
              label: "Marketplace",
              id: "sdk.thirdwebsdk.getmarketplace",
            },
            {
              type: "doc",
              label: "Multiwrap",
              id: "sdk.thirdwebsdk.getmultiwrap",
            },
            {
              type: "doc",
              label: "NFT Collection",
              id: "sdk.thirdwebsdk.getnftcollection",
            },
            {
              type: "doc",
              label: "NFT Drop",
              id: "sdk.thirdwebsdk.getnftdrop",
            },
            {
              type: "doc",
              label: "Pack",
              id: "sdk.thirdwebsdk.getpack",
            },
            {
              type: "doc",
              label: "Signature Drop",
              id: "sdk.thirdwebsdk.getsignaturedrop",
            },
            {
              type: "doc",
              label: "Split",
              id: "sdk.thirdwebsdk.getsplit",
            },
            {
              type: "doc",
              label: "Token",
              id: "sdk.thirdwebsdk.gettoken",
            },
            {
              type: "doc",
              label: "Token Drop",
              id: "sdk.thirdwebsdk.gettokendrop",
            },
            {
              type: "doc",
              label: "Vote",
              id: "sdk.thirdwebsdk.getvote",
            },
          ],
        },
      ],
    },
    // === Interacting with Contracts ===
    {
      type: "category",
      label: "Interacting with Contracts",
      items: [
        {
          type: "doc",
          label: "ERC721",
          id: "sdk.erc721",
        },
        {
          type: "doc",
          label: "ERC1155",
          id: "sdk.erc1155",
        },
        {
          type: "doc",
          label: "ERC20",
          id: "sdk.erc20",
        },
        // === Prebuilt Contracts ===
        {
          type: "category",
          label: "Prebuilt Contracts",
          items: [
            { type: "doc", label: "Edition", id: "sdk.editionimpl" },
            { type: "doc", label: "Edition Drop", id: "sdk.editiondropimpl" },
            { type: "doc", label: "Marketplace", id: "sdk.marketplaceimpl" },
            { type: "doc", label: "Multiwrap", id: "sdk.multiwrapimpl" },
            {
              type: "doc",
              label: "NFT Collection",
              id: "sdk.nftcollectionimpl",
            },
            { type: "doc", label: "NFT Drop", id: "sdk.nftdropimpl" },
            { type: "doc", label: "Pack", id: "sdk.packimpl" },
            {
              type: "doc",
              label: "Signature Drop",
              id: "sdk.signaturedropimpl",
            },
            { type: "doc", label: "Split", id: "sdk.splitimpl" },
            { type: "doc", label: "Token", id: "sdk.tokenimpl" },
            { type: "doc", label: "Token Drop", id: "sdk.tokendropimpl" },
            { type: "doc", label: "Vote", id: "sdk.voteimpl" },
          ],
        },
      ],
    },
    // === Contract Settings
    {
      type: "category",
      label: "Contract Settings",
      items: [
        {
          type: "doc",
          label: "Contract Owner",
          id: "sdk.contractowner",
        },
        {
          type: "doc",
          label: "Platform Fee",
          id: "sdk.contractplatformfee",
        },
        {
          type: "doc",
          label: "Primary Sales",
          id: "sdk.contractprimarysale",
        },
        {
          type: "doc",
          label: "Permission Controls",
          id: "sdk.contractroles",
        },
        {
          type: "doc",
          label: "Royalties",
          id: "sdk.contractroyalty",
        },
      ],
    },
    // === Wallet Actions ===
    {
      type: "category",
      label: "Wallet Information",
      items: [
        {
          type: "doc",
          label: "Wallet Actions",
          id: "sdk.userwallet",
        },
        {
          type: "doc",
          label: "Wallet Events",
          id: "sdk.userwalletevents",
        },
      ],
    },

    // === Signature Based Minting ===
    {
      type: "category",
      label: "Signature Based Minting",
      items: [
        {
          type: "doc",
          label: "ERC721",
          id: "sdk.erc721withquantitysignaturemintable",
        },
        {
          type: "doc",
          label: "ERC1155",
          id: "sdk.erc1155signaturemintable",
        },
        {
          type: "doc",
          label: "ERC20",
          id: "sdk.erc20signaturemintable",
        },
      ],
    },

    // === Contract Events ===
    {
      type: "doc",
      label: "Contract Events",
      id: "sdk.contractevents",
    },

    // === Advanced Features ===
    {
      type: "category",
      label: "Advanced Features",
      items: [
        {
          type: "doc",
          label: "Gasless Transactions",
          id: "sdk.gaslesstransaction",
        },
        {
          type: "doc",
          label: "Gas Cost Estimator",
          id: "sdk.gascostestimator",
        },
        {
          type: "doc",
          label: "Contract Interceptor",
          id: "sdk.contractinterceptor",
        },
      ],
    },

    // === Utilities ===
    {
      type: "category",
      label: "Utilities",
      items: [
        {
          type: "category",
          label: "Native Token Info",
          items: [
            {
              type: "doc",
              label: "Get Native Token By Chain",
              id: "sdk.getnativetokenbychainid",
            },
            {
              type: "doc",
              label: "Native Token Address",
              id: "sdk.native_token_address",
            },
          ],
        },
        {
          type: "doc",
          label: "Chain ID Enum",
          id: "sdk.chainid",
        },
      ],
    },

    {
      className: "hidden-category",
      type: "category",
      label: "Full Reference",
      collapsed: true,
      link: {
        type: "generated-index",
        title: "Full Reference",
        description: "Everything exported by the package",
      },
      items: [
        {
          type: "autogenerated",
          dirName: ".",
        },
      ],
      collapsible: false,
    },
  ],
};

module.exports = sidebars;
